# Generated by Django 5.2.1 on 2026-02-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('properties', '0003_rename_properties__status_6cf588_idx_properties__status_dc733e_idx_and_more'),
        ('room', '0005_booking_booking_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full_sync', 'Full Synchronization'), ('incremental_sync', 'Incremental Sync'), ('date_range', 'Date Range Sync')], help_text='Type of synchronization', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry Scheduled')], default='pending', help_text='Current status of this sync', max_length=20)),
                ('rooms_affected', models.IntegerField(blank=True, help_text='Number of rooms affected by this sync', null=True)),
                ('date_from', models.DateField(blank=True, help_text='Start date for range syncs', null=True)),
                ('date_to', models.DateField(blank=True, help_text='End date for range syncs', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('attempt_count', models.PositiveIntegerField(default=1, help_text='Number of attempts for this sync')),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP status code from channel API', null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Full response data from channel API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync completed or failed', null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to retry if failed', null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='channels.channel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_sync_logs', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'sync_status'], name='inventory_a_propert_4ca1ab_idx'), models.Index(fields=['channel', 'sync_status'], name='inventory_a_channel_831569_idx'), models.Index(fields=['created_at'], name='inventory_a_created_8d1e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this availability record')),
                ('total_units', models.PositiveIntegerField(default=1, help_text='Total rooms available on this date')),
                ('available_units', models.PositiveIntegerField(default=1, help_text='Number of rooms available for booking')),
                ('booked_units', models.PositiveIntegerField(default=0, help_text='Number of rooms already booked')),
                ('blocked_units', models.PositiveIntegerField(default=0, help_text='Number of rooms blocked (maintenance, cleaning, etc.)')),
                ('overbooked_units', models.PositiveIntegerField(default=0, help_text='Number of rooms overbooked (staff override)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price per night', max_digits=10, null=True)),
                ('dynamic_price', models.DecimalField(blank=True, decimal_places=2, help_text='Dynamic price per night (from pricing engine)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about availability (e.g., reason for blocking)')),
                ('staff_override', models.BooleanField(default=False, help_text='True if manually set by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='room.room')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who made the last update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room', 'date'],
                'indexes': [models.Index(fields=['room', 'date'], name='inventory_r_room_id_13a1db_idx'), models.Index(fields=['date'], name='inventory_r_date_6e5f58_idx'), models.Index(fields=['available_units'], name='inventory_r_availab_d6cce8_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='unique_room_availability_per_date')],
            },
        ),
    ]
