# Generated by Django 4.2.7 on 2026-02-20 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_properties__status_6cf588_idx_properties__status_dc733e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_schema_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='properties.travelagency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['travel_agency', 'user__first_name'],
                'indexes': [models.Index(fields=['travel_agency', 'is_active'], name='accounts_tr_travel__a16a7c_idx'), models.Index(fields=['user'], name='accounts_tr_user_id_6e2dd7_idx')],
                'unique_together': {('user', 'travel_agency')},
            },
        ),
    ]
