export const SIDEBAR_ITEMS = {
  admin: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: 'Dashboard' },
    { label: 'Users', path: '/admin/users', icon: 'People' },
    { label: 'Employees', path: '/admin/employees', icon: 'BadgeOutlined' },
    { label: 'Properties', path: '/admin/properties', icon: 'Business' },
    { label: 'Travel Agencies', path: '/admin/travel-agencies', icon: 'DirectionsBus' },
    { label: 'Rooms', path: '/admin/rooms', icon: 'MeetingRoom' },
    { label: 'Bookings', path: '/admin/bookings', icon: 'EventNote' },
    { label: 'Guests', path: '/admin/guests', icon: 'PersonOutline' },
    { label: 'Payments', path: '/admin/payments', icon: 'Payment' },
    { label: 'Invoices', path: '/admin/invoices', icon: 'Receipt' },
    { label: 'Refunds', path: '/admin/refunds', icon: 'MoneyOff' },
    { label: 'Contracts', path: '/admin/contracts', icon: 'Description' },
    { label: 'Events', path: '/admin/events', icon: 'Event' },
    { label: 'Tasks', path: '/admin/tasks', icon: 'Assignment' },
    { label: 'Room Services', path: '/admin/room-services', icon: 'RoomService' },
    { label: 'Announcements', path: '/admin/announcements', icon: 'Campaign' },
    { label: 'Storage', path: '/admin/storage', icon: 'Inventory' },
    { label: 'Dynamic Pricing', path: '/admin/pricing', icon: 'TrendingUp' },
    { label: 'OTA Channels', path: '/admin/channels', icon: 'CloudSync' },
    { label: 'Inventory', path: '/admin/inventory', icon: 'GridView' },
    { label: 'Analytics', path: '/analytics', icon: 'BarChart' },
    { label: 'Notifications', path: '/admin/notifications', icon: 'Notifications' },
  ],

  manager: [
    { label: 'Dashboard', path: '/manager/dashboard', icon: 'Dashboard' },
    { label: 'Bookings', path: '/manager/bookings', icon: 'EventNote' },
    { label: 'Rooms', path: '/manager/rooms', icon: 'MeetingRoom' },
    { label: 'Payments', path: '/manager/payments', icon: 'Payment' },
    { label: 'Events', path: '/manager/events', icon: 'Event' },
    { label: 'Contracts', path: '/manager/contracts', icon: 'Description' },
    { label: 'Tasks', path: '/manager/tasks', icon: 'Assignment' },
    { label: 'Announcements', path: '/manager/announcements', icon: 'Campaign' },
    { label: 'Analytics', path: '/manager/analytics', icon: 'BarChart' },
  ],

  receptionist: [
    { label: 'Dashboard', path: '/receptionist/dashboard', icon: 'Dashboard' },
    { label: 'Bookings', path: '/receptionist/bookings', icon: 'EventNote' },
    { label: 'Check-In / Out', path: '/receptionist/check-in', icon: 'HotelOutlined' },
    { label: 'Rooms', path: '/receptionist/rooms', icon: 'MeetingRoom' },
    { label: 'Guests', path: '/receptionist/guests', icon: 'People' },
    { label: 'Payments', path: '/receptionist/payments', icon: 'Payment' },
  ],

  staff: [
    { label: 'Dashboard', path: '/staff/dashboard', icon: 'Dashboard' },
    { label: 'Tasks', path: '/staff/tasks', icon: 'Assignment' },
  ],

  guest: [
    { label: 'Dashboard', path: '/guest/dashboard', icon: 'Dashboard' },
    { label: 'My Bookings', path: '/guest/bookings', icon: 'EventNote' },
    { label: 'Invoices', path: '/guest/invoices', icon: 'Receipt' },
    { label: 'Refunds', path: '/guest/refunds', icon: 'MoneyOff' },
    { label: 'Events', path: '/guest/events', icon: 'Event' },
    { label: 'Room Services', path: '/guest/room-services', icon: 'RoomService' },
    { label: 'Notifications', path: '/guest/notifications', icon: 'Notifications' },
    { label: 'Profile', path: '/guest/profile', icon: 'AccountCircle' },
    { label: 'Privacy & Data', path: '/guest/privacy', icon: 'Shield' },
  ],
}
