# Generated by Django 4.2.7 on 2026-02-20 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_travelagency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='travelagency',
            new_name='properties__status_dc733e_idx',
            old_name='properties__status_6cf588_idx',
        ),
        migrations.RenameIndex(
            model_name='travelagency',
            new_name='properties__email_f69ac3_idx',
            old_name='properties__email_58b4d9_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(help_text='Hotel manager responsible for this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'country'], name='properties__city_45e90f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'),
        ),
    ]
