# Generated by Django 5.2.1 on 2026-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_travelagentprofile'),
        ('payments', '0001_initial'),
        ('room', '0005_booking_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mydata_cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_cancel_mark',
            field=models.CharField(blank=True, help_text='MyData cancellation mark if applicable', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_qr_code',
            field=models.TextField(blank=True, help_text='QR Code data for MyData'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_transmission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_transmission_id',
            field=models.CharField(blank=True, help_text='MyData transmission ID/mark', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_transmitted',
            field=models.BooleanField(default=False, help_text='Whether invoice was transmitted to MyData'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['mydata_transmitted'], name='payments_in_mydata__2230a2_idx'),
        ),
    ]
