#!/usr/bin/env bash
# Task 3 Data Directory Index
# Quick reference for all files and their purposes

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "NEPHELE HOTEL MANAGEMENT SYSTEM - TASK 3 DATA DIRECTORY"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📁 TRAINING DATASETS (CSV Files)"
echo "───────────────────────────────────────────────────────────────────────────────"
echo ""
echo "┌─ CORE DATASETS FOR ML TRAINING"
echo "│"
echo "├─ bookings.csv (24,260+ records)"
echo "│  ├─ Purpose: Dynamic pricing model training"
echo "│  ├─ Key fields: guest_id, room_id, nightly_rate, booking_date, check_in_date"
echo "│  ├─ Size: ~3.0 MB"
echo "│  └─ Usage: Main training dataset for pricing optimization"
echo "│"
echo "├─ guest_preferences.csv (25,188 records)"
echo "│  ├─ Purpose: Recommendation system training"
echo "│  ├─ Key fields: guest_id, room_id, wants_breakfast, preferred_view, rating"
echo "│  ├─ Size: ~1.8 MB"
echo "│  └─ Usage: Content-based & collaborative filtering"
echo "│"
echo "├─ pricing_history.csv (10,960 records)"
echo "│  ├─ Purpose: Time-series forecasting & BI analysis"
echo "│  ├─ Key fields: date, occupancy_rate, average_nightly_rate, season"
echo "│  ├─ Size: ~614 KB"
echo "│  └─ Usage: Trend analysis, demand forecasting"
echo "│"
echo "├─ competitor_pricing.csv (43,738 records)"
echo "│  ├─ Purpose: Market intelligence for pricing algorithms"
echo "│  ├─ Key fields: date, competitor_id, competitor_price, competitor_available_rooms"
echo "│  ├─ Size: ~2.5 MB"
echo "│  └─ Usage: Competitive pricing strategies"
echo "│"
echo "└─ SUPPORTING DATASETS"
echo "   │"
echo "   ├─ guests.csv (5,000 records)"
echo "   │  ├─ Purpose: Guest segmentation & personalization"
echo "   │  ├─ Size: ~453 KB"
echo "   │  └─ Usage: Customer RFM analysis, loyalty tracking"
echo "   │"
echo "   ├─ rooms.csv (300 records)"
echo "   │  ├─ Purpose: Room features for recommendations"
echo "   │  ├─ Size: ~37 KB"
echo "   │  └─ Usage: Content-based similarity calculations"
echo "   │"
echo "   └─ properties.csv (10 records)"
echo "      ├─ Purpose: Hotel master data"
echo "      ├─ Size: ~0.9 KB"
echo "      └─ Usage: Multi-property aggregation"
echo ""
echo "📚 DOCUMENTATION FILES"
echo "───────────────────────────────────────────────────────────────────────────────"
echo ""
echo "├─ README.md"
echo "│  └─ Complete dataset documentation with data dictionary, column descriptions,"
echo "│     and integration examples"
echo "│"
echo "├─ SUMMARY.md"
echo "│  └─ Executive summary with data statistics, quality assurance checklist,"
echo "│     and next steps"
echo "│"
echo "├─ django_models_template.py"
echo "│  └─ Django ORM model templates for database integration"
echo "│"
echo "└─ INDEX.sh (this file)"
echo "   └─ Quick reference guide for all files"
echo ""
echo "🔧 UTILITY SCRIPTS"
echo "───────────────────────────────────────────────────────────────────────────────"
echo ""
echo "├─ generate_synthetic_data.py (380 lines)"
echo "│  ├─ Purpose: Generates all 7 CSV datasets"
echo "│  ├─ Usage: python3 generate_synthetic_data.py"
echo "│  └─ Customizable: Edit class parameters for different data volumes"
echo "│"
echo "└─ inspect_data.py (35 lines)"
echo "   ├─ Purpose: Displays data structure and sample records"
echo "   ├─ Usage: python3 inspect_data.py"
echo "   └─ Output: Column names, types, and first 3 rows of each dataset"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "QUICK START"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. View data structure:"
echo "   $ python3 task3-data/inspect_data.py"
echo ""
echo "2. Load in Python:"
echo "   >>> import pandas as pd"
echo "   >>> bookings = pd.read_csv('task3-data/bookings.csv')"
echo "   >>> print(f'Loaded {len(bookings)} bookings')"
echo ""
echo "3. Import to Django:"
echo "   $ python manage.py import_training_data --csv-dir task3-data/"
echo ""
echo "4. Train models:"
echo "   >>> from task3_data import PricingModel"
echo "   >>> model = PricingModel()"
echo "   >>> model.load_data('task3-data/bookings.csv')"
echo "   >>> model.train()"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "DATA STATISTICS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 Total Records: 109,356"
echo "💾 Total Size: 8.3 MB"
echo "📅 Time Period: Jan 1, 2022 - Dec 31, 2024 (24 months)"
echo "🏨 Properties: 10 hotels across Greece"
echo "🛏️ Rooms: 300 (30 per property)"
echo "👥 Guests: 5,000 unique profiles"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "USE CASES"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Dynamic Pricing Algorithms"
echo "   • Predict optimal room prices based on demand, seasonality, competition"
echo "   • Revenue optimization and yield management"
echo "   • Price elasticity analysis"
echo ""
echo "✅ Personalization & Recommendations"
echo "   • Content-based filtering (similar rooms)"
echo "   • Collaborative filtering (similar guests)"
echo "   • Hybrid recommendations with business rules"
echo ""
echo "✅ Business Intelligence & Analytics"
echo "   • Occupancy forecasting"
echo "   • Revenue per available room (RevPAR) analysis"
echo "   • Customer segmentation (RFM analysis)"
echo "   • Seasonal trend identification"
echo ""
echo "✅ Demand Forecasting"
echo "   • Time-series analysis and prediction"
echo "   • Booking velocity analysis"
echo "   • Holiday and event impact modeling"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "DATA QUALITY ASSURANCE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✓ Referential Integrity - All foreign keys valid"
echo "✓ Business Logic - Prices > 0, occupancy in [0,1], check-out > check-in"
echo "✓ Realistic Distributions - Seasonal patterns, lead time bias"
echo "✓ Complete Coverage - 24 months, 10 properties, diverse booking channels"
echo "✓ GDPR Compliant - Synthetic data (no real personal information)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "FILE SIZES & RECORD COUNTS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

# Display actual file information
ls -lh *.csv 2>/dev/null | awk '
{printf "%-35s %10s\n", $9, $5}' && echo ""

wc -l *.csv 2>/dev/null | grep total | awk '{print "Total lines across all CSV files: " $1}' && echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "RECOMMENDATION: Start with README.md and SUMMARY.md"
echo "═══════════════════════════════════════════════════════════════════════════════"
