# Generated by Django 4.2.7 on 2026-02-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_schema_alignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='room_bookin_room_id_8d6b79_idx',
            old_name='room_booking_room_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='room_bookin_guest_i_1cc7f2_idx',
            old_name='room_booking_guest_status_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='room_bookin_status_9466a2_idx',
            old_name='room_booking_status_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_room_propert_b48fca_idx',
            old_name='room_room_property_status_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_room_room_nu_b68505_idx',
            old_name='room_room_room_number_idx',
        ),
        migrations.RenameIndex(
            model_name='roomservice',
            new_name='room_roomse_room_id_9200c9_idx',
            old_name='room_roomservice_room_status_idx',
        ),
        migrations.RenameIndex(
            model_name='roomservice',
            new_name='room_roomse_created_3822a0_idx',
            old_name='room_roomservice_created_idx',
        ),
    ]
