# Generated by Django 4.2.7 on 2026-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_room_booking_room_dates_idx_room_bookin_room_id_8d6b79_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('direct_website', 'Direct Website'), ('booking_com', 'Booking.com'), ('trivago', 'Trivago'), ('phone', 'Phone Call'), ('travel_agency', 'Travel Agency'), ('other', 'Other')], default='direct_website', help_text='Source of the booking (used only if no travel agency selected)', max_length=20),
        ),
    ]
