# Auto-generated migration for analytics application

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardExecutiveMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('revpar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_count', models.IntegerField(default=0)),
                ('revenue_trend_30d', models.JSONField(blank=True, default=dict)),
                ('occupancy_trend_30d', models.JSONField(blank=True, default=dict)),
                ('adr_trend_30d', models.JSONField(blank=True, default=dict)),
                ('yoy_revenue_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yoy_occupancy_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_metrics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Executive Metrics',
                'verbose_name_plural': 'Executive Metrics',
                'db_table': 'dashboard_executive_metrics',
            },
        ),
        migrations.CreateModel(
            name='DashboardOperationalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('status_time', models.DateTimeField()),
                ('occupied_count', models.IntegerField(default=0)),
                ('vacant_count', models.IntegerField(default=0)),
                ('cleaning_count', models.IntegerField(default=0)),
                ('maintenance_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('checkouts_scheduled', models.IntegerField(default=0)),
                ('checkins_scheduled', models.IntegerField(default=0)),
                ('housekeeping_tasks_pending', models.IntegerField(default=0)),
                ('housekeeping_tasks_in_progress', models.IntegerField(default=0)),
                ('maintenance_tickets_pending', models.IntegerField(default=0)),
                ('active_guests_count', models.IntegerField(default=0)),
                ('guests_with_special_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_status', to='properties.property')),
            ],
            options={
                'verbose_name': 'Operational Status',
                'verbose_name_plural': 'Operational Statuses',
                'db_table': 'dashboard_operational_status',
            },
        ),
        migrations.CreateModel(
            name='DashboardRevenueMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_direct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_ota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_agency', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revpar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dynamic_pricing_uplift', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('occupancy_count', models.IntegerField(blank=True, null=True)),
                ('booking_count', models.IntegerField(default=0)),
                ('cancellation_count', models.IntegerField(default=0)),
                ('cancellation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('noshow_count', models.IntegerField(default=0)),
                ('revenue_forecast_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occupancy_forecast_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metrics_by_source', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_metrics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Revenue Metrics',
                'verbose_name_plural': 'Revenue Metrics',
                'db_table': 'dashboard_revenue_metrics',
            },
        ),
        migrations.CreateModel(
            name='DashboardGuestAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_date', models.DateField()),
                ('total_unique_guests', models.IntegerField(default=0)),
                ('new_guests', models.IntegerField(default=0)),
                ('returning_guests', models.IntegerField(default=0)),
                ('repeat_booking_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_booking_lead_days', models.IntegerField(blank=True, null=True)),
                ('avg_length_of_stay', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_review_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('avg_nps', models.IntegerField(blank=True, null=True)),
                ('review_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complaint_count', models.IntegerField(default=0)),
                ('complaint_resolution_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retention_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('churn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('at_risk_guests', models.IntegerField(default=0)),
                ('recommendations_generated', models.IntegerField(default=0)),
                ('recommendations_accepted', models.IntegerField(default=0)),
                ('upsell_conversions', models.IntegerField(default=0)),
                ('cross_sell_conversions', models.IntegerField(default=0)),
                ('personalization_revenue_uplift', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('guest_segments', models.JSONField(blank=True, default=dict)),
                ('geographic_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_analytics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Guest Analytics',
                'verbose_name_plural': 'Guest Analytics',
                'db_table': 'dashboard_guest_analytics',
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('revenue', 'Revenue Report'), ('occupancy', 'Occupancy Report'), ('guest', 'Guest Analytics Report'), ('pricing', 'Pricing Analysis Report'), ('custom', 'Custom Report')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_detailed_data', models.BooleanField(default=True)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='properties.property')),
            ],
            options={
                'verbose_name': 'Custom Report',
                'verbose_name_plural': 'Custom Reports',
                'db_table': 'custom_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('daily_operational', 'Daily Operational Dashboard'), ('daily_finance', 'Daily Finance Report'), ('weekly_performance', 'Weekly Performance Report'), ('weekly_marketing', 'Weekly Marketing Report'), ('monthly_executive', 'Monthly Executive Summary'), ('monthly_occupancy', 'Monthly Occupancy Analysis'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=30)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Cron')], max_length=20)),
                ('schedule_day', models.IntegerField(blank=True, help_text='Day of month for monthly reports (1-31)', null=True)),
                ('schedule_dow', models.IntegerField(blank=True, help_text='Day of week for weekly reports (0=Monday, 6=Sunday)', null=True)),
                ('schedule_time', models.TimeField(help_text='Time to generate report (UTC)')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('recipient_emails', models.JSONField(default=list, help_text='Array of email addresses')),
                ('include_managers', models.BooleanField(default=True)),
                ('include_owner', models.BooleanField(default=False)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_detailed_data', models.BooleanField(default=True)),
                ('custom_filters', models.JSONField(blank=True, default=dict)),
                ('metric_selection', models.JSONField(blank=True, default=dict)),
                ('export_formats', models.JSONField(default=list, help_text='Export formats: pdf, excel, csv')),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='properties.property')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'db_table': 'scheduled_reports',
                'ordering': ['is_active', 'schedule_time'],
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('excel_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('csv_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('email_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(default=list)),
                ('data_date_from', models.DateField()),
                ('data_date_to', models.DateField()),
                ('metrics_snapshot', models.JSONField(default=dict, help_text='Snapshot of KPIs for this report')),
                ('execution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.scheduledreport')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDeliveryTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('email_provider_id', models.CharField(blank=True, help_text='SendGrid message ID or similar', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='analytics.reportexecution')),
            ],
            options={
                'verbose_name': 'Report Delivery Tracking',
                'verbose_name_plural': 'Report Delivery Tracking',
                'db_table': 'report_delivery_tracking',
                'ordering': ['-created_at'],
                'unique_together': {('report_execution', 'recipient_email')},
            },
        ),
        migrations.AddIndex(
            model_name='dashboardexecutivemetrics',
            index=models.Index(fields=['property', 'metric_date'], name='dashboard_e_property_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardexecutivemetrics',
            index=models.Index(fields=['metric_date'], name='dashboard_e_metric_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardoperationalstatus',
            index=models.Index(fields=['property', 'status_date', 'status_time'], name='dashboard_o_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardoperationalstatus',
            index=models.Index(fields=['property', 'status_date'], name='dashboard_o_property_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrevenuemetrics',
            index=models.Index(fields=['property', 'metric_date'], name='dashboard_r_property_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardrevenuemetrics',
            index=models.Index(fields=['metric_date'], name='dashboard_r_metric_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardguestanalytics',
            index=models.Index(fields=['property', 'analytics_date'], name='dashboard_g_property_analytics_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardguestanalytics',
            index=models.Index(fields=['analytics_date'], name='dashboard_g_analytics_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customreport',
            index=models.Index(fields=['property', '-created_at'], name='custom_reports_property_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['property', 'is_active'], name='scheduled_r_property_is_active'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['next_scheduled_at'], name='scheduled_r_next_sch_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['is_active', 'next_scheduled_at'], name='scheduled_r_is_activ_next_sch'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['scheduled_report', '-created_at'], name='report_exec_scheduled_created'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['execution_status'], name='report_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['email_status'], name='report_exec_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['created_at'], name='report_exec_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdeliverytracking',
            index=models.Index(fields=['report_execution'], name='report_deli_execution_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdeliverytracking',
            index=models.Index(fields=['recipient_email'], name='report_deli_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdeliverytracking',
            index=models.Index(fields=['delivery_status'], name='report_deli_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdeliverytracking',
            index=models.Index(fields=['opened_at'], name='report_deli_opened_idx'),
        ),
    ]
