# Generated by Django 4.2.7 on 2026-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_properties__status_6cf588_idx_properties__status_dc733e_idx_and_more'),
        ('analytics', '0002_forecasting_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customreport',
            new_name='custom_repo_propert_edd07d_idx',
            old_name='custom_reports_property_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardexecutivemetrics',
            new_name='dashboard_e_propert_5d9e78_idx',
            old_name='dashboard_e_property_metric_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardexecutivemetrics',
            new_name='dashboard_e_metric__3496e1_idx',
            old_name='dashboard_e_metric_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardguestanalytics',
            new_name='dashboard_g_propert_34a2d5_idx',
            old_name='dashboard_g_property_analytics_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardguestanalytics',
            new_name='dashboard_g_analyti_58f057_idx',
            old_name='dashboard_g_analytics_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardoperationalstatus',
            new_name='dashboard_o_propert_143dab_idx',
            old_name='dashboard_o_property_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardoperationalstatus',
            new_name='dashboard_o_propert_e1020e_idx',
            old_name='dashboard_o_property_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardrevenuemetrics',
            new_name='dashboard_r_propert_9e3013_idx',
            old_name='dashboard_r_property_metric_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardrevenuemetrics',
            new_name='dashboard_r_metric__0f05cb_idx',
            old_name='dashboard_r_metric_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdeliverytracking',
            new_name='report_deli_report__d99d6f_idx',
            old_name='report_deli_execution_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdeliverytracking',
            new_name='report_deli_recipie_a887e8_idx',
            old_name='report_deli_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdeliverytracking',
            new_name='report_deli_deliver_105a75_idx',
            old_name='report_deli_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reportdeliverytracking',
            new_name='report_deli_opened__2c170e_idx',
            old_name='report_deli_opened_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_schedul_e702a3_idx',
            old_name='report_exec_scheduled_created',
        ),
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_executi_179999_idx',
            old_name='report_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_email_s_4ff104_idx',
            old_name='report_exec_email_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_created_6965fd_idx',
            old_name='report_exec_created_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_propert_0cd25a_idx',
            old_name='scheduled_r_property_is_active',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_next_sc_7fd672_idx',
            old_name='scheduled_r_next_sch_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_is_acti_893352_idx',
            old_name='scheduled_r_is_activ_next_sch',
        ),
        migrations.AlterField(
            model_name='customreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardexecutivemetrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardguestanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardoperationalstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardrevenuemetrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportdeliverytracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardexecutivemetrics',
            unique_together={('property', 'metric_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardrevenuemetrics',
            unique_together={('property', 'metric_date')},
        ),
    ]
