"""
Analytics app migrations - placeholder for auto-generated migrations
Run: python manage.py makemigrations analytics
Then: python manage.py migrate
"""

# This file will be auto-generated by Django
# To create migrations for the analytics app, run:
# python manage.py makemigrations analytics

# The following models will have migrations:
# - DashboardExecutiveMetrics
# - DashboardOperationalStatus
# - DashboardRevenueMetrics
# - DashboardGuestAnalytics
# - CustomReport
