# Generated by Django 5.2.1 on 2026-02-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_rename_properties__status_6cf588_idx_properties__status_dc733e_idx_and_more'),
        ('room', '0005_booking_booking_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(choices=[('booking_com', 'Booking.com'), ('trivago', 'Trivago'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('agoda', 'Agoda'), ('vrbo', 'VRBO'), ('booking_buddy', 'Booking Buddy'), ('hotwire', 'Hotwire'), ('travelocity', 'Travelocity'), ('priceline', 'Priceline'), ('orbitz', 'Orbitz'), ('kayak', 'Kayak'), ('hostelworld', 'HostelWorld'), ('ctrip', 'Ctrip'), ('custom', 'Custom OTA')], help_text='OTA platform name', max_length=50)),
                ('channel_type', models.CharField(choices=[('ota', 'Online Travel Agency'), ('metasearch', 'Metasearch Engine'), ('direct', 'Direct Booking')], default='ota', max_length=50)),
                ('account_id', models.CharField(help_text='Channel account ID or username', max_length=255)),
                ('api_key', models.CharField(help_text='API key for authentication', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='Optional API secret for webhook signing', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this channel')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Sync availability to this channel')),
                ('accept_bookings', models.BooleanField(default=True, help_text='Accept incoming bookings from this channel')),
                ('mapping_config', models.JSONField(blank=True, default=dict, help_text='\n        Configuration for mapping NEPHELE room IDs to channel room IDs.\n        Format: {\n            "room_mappings": {"123": "channel_room_id"},\n            "rate_mappings": {"123": "rate_code"},\n            "sync_overrides": {...}\n        }\n        ')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful synchronization timestamp', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message from channel API')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive sync failures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_booking_id', models.CharField(help_text='Booking ID from the external channel', max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('cancelled', 'Cancelled')], default='synced', max_length=20)),
                ('channel_data', models.JSONField(blank=True, default=dict, help_text='Full booking data from channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_bookings', to='channels.channel')),
                ('nephele_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_bookings', to='room.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['property', 'is_active'], name='channels_ch_propert_e27e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_name'], name='channels_ch_channel_fab298_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['last_sync_at'], name='channels_ch_last_sy_dfef0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('property', 'channel_name'), name='unique_channel_per_property'),
        ),
        migrations.AddIndex(
            model_name='channelbooking',
            index=models.Index(fields=['channel', 'channel_booking_id'], name='channels_ch_channel_80305c_idx'),
        ),
        migrations.AddIndex(
            model_name='channelbooking',
            index=models.Index(fields=['nephele_booking'], name='channels_ch_nephele_60dcec_idx'),
        ),
        migrations.AddIndex(
            model_name='channelbooking',
            index=models.Index(fields=['sync_status'], name='channels_ch_sync_st_28ac3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelbooking',
            constraint=models.UniqueConstraint(fields=('channel', 'channel_booking_id'), name='unique_channel_booking'),
        ),
    ]
