# Generated by Django 4.2.7 on 2026-02-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_status_aa7a80_idx',
            old_name='contracts_c_status_1d6701_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_propert_c81e9f_idx',
            old_name='contracts_c_propert_5d6174_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_start_d_f953e0_idx',
            old_name='contracts_c_start_d_156a87_idx',
        ),
    ]
