# Generated by Django 4.2.7 on 2026-02-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='competitorprice',
            new_name='bookings_co_room_id_41c57d_idx',
            old_name='bookings_co_room_id_27128a_idx',
        ),
        migrations.RenameIndex(
            model_name='demandforecast',
            new_name='bookings_de_room_id_b5cc82_idx',
            old_name='bookings_de_room_id_74f8f4_idx',
        ),
        migrations.RenameIndex(
            model_name='pricinghistory',
            new_name='bookings_pr_room_id_9f730d_idx',
            old_name='bookings_pr_room_id_a7772b_idx',
        ),
        migrations.RenameIndex(
            model_name='pricinghistory',
            new_name='bookings_pr_date_4114c9_idx',
            old_name='bookings_pr_date_6ad651_idx',
        ),
        migrations.RenameIndex(
            model_name='pricinghistory',
            new_name='bookings_pr_room_id_adea9c_idx',
            old_name='bookings_pr_room_id_e4f4b8_idx',
        ),
    ]
