# Generated by Django 5.2.1 on 2026-02-20 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookings_co_room_id_27128a_idx_bookings_co_room_id_41c57d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinghistory',
            name='ai_recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI recommended price at time of creation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='competitor_impact_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage impact from competitor pricing', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='demand_impact_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage impact from demand', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='ensemble_prediction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ensemble model price prediction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='gradient_boosting_prediction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gradient Boosting model price prediction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='linear_regression_prediction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Linear Regression model price prediction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='neural_network_prediction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Neural Network model price prediction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='occupancy_impact_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage impact from occupancy', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='override_by_user',
            field=models.ForeignKey(blank=True, help_text='User who overrode AI recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='price_override_reason',
            field=models.CharField(blank=True, help_text='Reason for manual price override', max_length=200),
        ),
        migrations.AddField(
            model_name='pricinghistory',
            name='seasonal_impact_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage impact from seasonality', max_digits=6, null=True),
        ),
    ]
